language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
# Support library
    - extra-android-support
    - extra-android-m2repository
    
env:
  global:
    # Used by CodeClimate coverage reporter
    - CC_TEST_REPORTER_ID=9ef8b6d6b9f83eef113e5393091f8587e7813756fcc8c8540d4404e93dbba257
    
before_script:
    - chmod +x gradlew
    # Code climate test coverage
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
   - chmod +x ./gradlew
   - ./gradlew assembleDebug assembleRelease
   - ./gradlew checkstyle
   - ./gradlew test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
